Interfaz de usuario con pantalla de inicio, conexion bluetooth y búsqueda automática. Interfaz de usuario pantalla de juego.
juanelobono/messibot pull request #18
Opened 2018-05-10 15:32 UTC by martinbaldassin

2018-05-10 16:06 UTC, matiasbeltramone commented on app/src/main/java/com/arquitecturasmoviles/messibot/DeviceListAdapter.java
> +            /*TextView deviceAdress = (TextView) convertView.findViewById(R.id.tvDeviceAddress);*/
A que se debe que se comente este codigo?

2018-05-10 16:07 UTC, matiasbeltramone commented on app/src/main/java/com/arquitecturasmoviles/messibot/MainActivity.java
>      //Button btnStartConnection;
Codigo comentado, codigo que debe ser eliminado

2018-05-10 16:08 UTC, matiasbeltramone commented on app/src/main/java/com/arquitecturasmoviles/messibot/MainActivity.java
> +//                if(mBluetoothAdapter.getBondedDevices().size() > 0){
el if else estan comentados , si no se utiliza q se elimine

2018-05-10 16:09 UTC, matiasbeltramone commented on app/src/main/res/layout/activity_joystick.xml
> +    <!--<io.github.controlwear.virtual.joystick.android.JoystickView xmlns:custom="http://schemas.android.com/apk/res-auto"-->
Si esto no se usa que se borre

2018-05-10 16:12 UTC, matiasbeltramone requested changes
Revisa los comments

2018-05-10 16:19 UTC, martinbaldassin commented on app/src/main/java/com/arquitecturasmoviles/messibot/DeviceListAdapter.java
> +            /*TextView deviceAdress = (TextView) convertView.findViewById(R.id.tvDeviceAddress);*/
eso es uno de los textos que muestra la lista de dispositivos bluetooth, es el que mostraba la MAC Address, lo comenté para que visualmente quede mas prolijo y para que, si en algun caso se necesita sepamos de donde obtener la MAC del dispositivo

2018-05-10 16:19 UTC, martinbaldassin commented on app/src/main/java/com/arquitecturasmoviles/messibot/MainActivity.java
>      //Button btnStartConnection;
Ok.

2018-05-10 16:53 UTC, fdvatri requested changes
{{ Aprobado con errores para integrar y testear lo antes posible. Comentarios entre doble llaves }}

REVISIÓN DE CÓDIGO (FUNCIONAL):

Condiciones de testeo:
- Dispositivo Android 7.0, API 24
- Dispositivo Android 6.0, API 23

Según lo declarado en los requerimientos:
- El joystick reacciona al movimiento con el dedo: OK
- El joystick traduce correctamente las posiciones en sentido (ángulo) y aceleración (strenght): NO *1
- Se activa el Bluetooth: OK
- No se activa el Bluetooth al cancelar la confirmación: OK
- Se activa/desactiva el Bluetooth de la aplicación si se manipula el estado del Bluetooth por fuera de la misma: OK
- Se listan los dispositivos disponibles y es posible enlazar con uno de ellos: NO 2*

Observaciones:
1* La fuerza en decimal nunca llega a 255 en ciertos puntos; se llega hasta 252 como máximo. {{ No es impedimento para el movimiento del robot, ya que el margen es demasiado pequeño para ocasionar diferencias notables en la aceleración }}
2* Teniendo varios dispositivos cercanos para testear la conexión, no hubo manera que la aplicación detectara alguno de ellos, incluso luego de 5 minutos de espera. {{ No se volvió a presentar el error a retestear en el mismo entorno }}

Extras:
- Estando en el layout del joystick, la aplicación se detiene (al azar) al querer volver al menú principal con la flecha de retroceso. Detalle del error a continuación por Logcat:
{05-10 23:01:37.110 12900-12900/com.arquitecturasmoviles.messibot E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.arquitecturasmoviles.messibot, PID: 12900
    java.lang.RuntimeException: Unable to destroy activity {com.arquitecturasmoviles.messibot/com.arquitecturasmoviles.messibot.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.arquitecturasmoviles.messibot.MainActivity$5@40295c6
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
        at android.app.ActivityThread.-wrap7(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.arquitecturasmoviles.messibot.MainActivity$5@40295c6
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1376)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:668)
        at com.arquitecturasmoviles.messibot.MainActivity.onDestroy(MainActivity.java:53)
        at android.app.Activity.performDestroy(Activity.java:7223)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661) 
        at android.app.ActivityThread.-wrap7(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) }
{{ Hay un conflicto de versiones. Este error surge solamente en Android 6+, y es consecuencia del punto siguiente }}

- El botón "Jugar" funciona siempre; aún cuando no se ha conectado a ningún dispositivo que amerite iniciar la partida. {{ Hay un conflicto de versiones. Este error surge solamente en Android 6+ }}

2018-05-12 00:28 UTC, fdvatri approved these changes

2018-05-12 00:41 UTC, matiasbeltramone approved these changes

2018-05-12 01:17 UTC, merged